# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a440347dc4bb91a753e95e3007cfd6e6f77f310ccc2ebb2192acc2fb2b7e15819942cf5caf6397dc351a189ecff83a1e60125ae3bcf01df482f3bf486e8c0013

test:
  secret_key_base: 30e866cadba47911fed1685809d70c1ce09912b57e0eac88fef122e95a3dfbe304028a9e977e8e1b7add04db9bba683634e215b6ca71416d2f9a9dd70eb74ba1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
